# Generated by Django 3.1.7 on 2021-04-12 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_contacthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacthistory',
            options={'verbose_name_plural': 'Contact history'},
        ),
        migrations.AlterField(
            model_name='contacthistory',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
