# Generated by Django 3.1.7 on 2021-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=True),
        ),
    ]
