# Generated by Django 3.1.7 on 2021-04-11 06:43

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_auto_20210409_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=31, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(default='default.png', upload_to=customers.models.user_directory_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, editable=False, upload_to='')),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('FACEBOOK', 'Facebook'), ('TELEGRAM', 'Telegram'), ('INSTAGRAM', 'Instagram')], max_length=16)),
                ('value', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer')),
            ],
        ),
    ]
