# Generated by Django 3.1.7 on 2021-04-15 09:00

import customers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('note', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(default='default.png', upload_to=customers.models.user_directory_path)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
                ('preferred_products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
