# Generated by Django 3.1.7 on 2021-04-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='preferred_products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
    ]
