# Generated by Django 3.1.7 on 2021-04-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210411_0953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
