# Generated by Django 3.1.7 on 2021-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210409_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='note',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
