# Generated by Django 3.1.7 on 2021-04-11 05:15

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210409_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=customers.models.user_directory_path),
        ),
    ]
